### ISSUE TITLE
Grace note value changes with key

### ISSUE THREAD

**Issue by sbeitzel** [leesavide/abcm2ps#1]
If a tune is noted as being in the "key" of bagpipe (K:HP) then grace notes will be drawn as small 32nd notes. However, if the tune is noted as being in the key of D (K:D), which is how bagpipes are tuned, then grace notes are drawn as small 1/8th notes. Some modern composers, notably Fred Morrison and Gordon Duncan, have made wide use of C-natural and so there are many tunes that are written for bagpipes and which are really not in the key of D but in G. It'd be nice to be able to provide a formatting directive at the top of the tune to specify the drawn time value of a grace note, similar to the "L:" field.

`%%gracenotelength 1/32` for example, while the default (for tunes not in the key of HP) would be `%%gracenotelength 1/8`.

I understand that this would represent an extension to the existing ABC music standard and would have to go through discussion and voting, etc. But in the interim, what about an application specific directive? `%%abcm2ps:gracenotelength 1/32`

**Comment by lewdlime** [comment]
Closing this since I'm not the owner of the original code.
