### ISSUE TITLE
"Bad length" for legit 7/8 duration

### ISSUE THREAD

**Issue by ciacob** [leesavide/abcm2ps#106]
Version `abcm2ps-8.14.12 (2021-07-14)` produces a **Bad length** error for something like `C7/8` in ABC source code. 

**This duration is legit, and it is represented as a _[double dotted](https://en.wikipedia.org/wiki/Dotted_note#Double_dotting) half_** by version `abcm2ps-8.13.12 (July 3, 2017)`.

I could go on ignoring the error, but `abcm2ps-8.14.12 (2021-07-14)` "auto-corrects" the music by only rendering _one eight_ out of the expected _double dotted half_, which in turn causes vertical alignment to break.

Check e.g. first voice of third measure of attached [test 2.pdf](https://github.com/lewdlime/abcm2ps/files/7532421/test.2.pdf).

Compare that with same first voice of third measure of attached [test.pdf](https://github.com/lewdlime/abcm2ps/files/7532424/test.pdf) (this one was generated by older version `abcm2ps-8.13.12 (July 3, 2017)`).

PDFs were generated with [ghostscript](https://www.ghostscript.com/).

ABC code used as source for **both** PDFs is in [test.txt](https://github.com/lewdlime/abcm2ps/files/7532428/test.txt).

**Comment by moinejf** [comment]
The bug is fixed by the commit 7e8986e.
The problem was not seen before because your unit length is big (L:1/1).
Thanks for the report.

**Comment by ciacob** [comment]
Thanks for fixing!
