### ISSUE TITLE
Error with redefinable symbol

### ISSUE THREAD

**Issue by sbeitzel** [leesavide/abcm2ps#11]
The [ABC standard suggests](http://abcnotation.com/wiki/abc:standard:v2.1#redefinable_symbols) that one ought to be able to redefine a symbol to include an annotation. However, abcm2ps seems to treat any such definition as needing to be a decoration string. For example, the following ABC file:

`%abc-2.1
%%straightflags false
%%flatbeams true
%%graceslurs false
%%titleformat T0, R-1 C1
X: 1
T: Moonstar (SNARE)
C: arr. by Gloria Pellegrin
M: 4/4
L: 1/8
K: none stafflines=1
V: S stem=down gstem=up dyn=up clef=none snm="S"
U: R = ///
U: r = //
U: v = "^V"
V:S
{A}c>A r(cA) {A}cvrc`

produces this error output:
`abcm2ps-8.13.17 (2017-11-21)
File moonstar_snare.abc
moonstar_snare.abc:17:19: error: Decoration !"^V"! not defined`

Whereas, if the line is changed to:
`{A}c>A r(cA) {A}c"^V"rc`
then the output looks the way one expects, with a 'V' appearing above the last note.

**Comment by moinejf** [comment]
abcm2ps does not implement all of the ABC standard. The differences are described in the document: http://moinejf.free.fr/abcm2ps-doc/features.xhtml.

**Comment by sbeitzel** [comment]
Fair enough.
