### ISSUE TITLE
Repeat barline problem on multiple voices

### ISSUE THREAD

**Issue by jnbearon** [leesavide/abcm2ps#13]
There seems to have been a problem for a while now with opening repeat bar lines not going through to multiple voices when at the start of a new line.  It only seems to apply to the second one in a file

Example

X:9
T:Indian Queen, The
Q:1/2=110
S:Playford
%%scale=0.75
M:2/2
L:1/4
K:D
V:1
"^A" |: f/g/ | "D"af df | "A"e2 A2 | "D"FA Af | "A"e2 - ef/g/ | 
D"af df | "A"e2 A2 | "D"FA Af | "D"d3 :|
"^B" |: c/d/ | "A"e/d/c/B/ Ae | "F#m"fc "Bm"dB | "D"f/g/a "E"b^g | "A"a3e/f/ |\
"G"g/f/e/d/ "A"ca | "G"Bg "D"Af/g/ | "G"ed "A"ec | "D"d3 :|
V:2
|: f/g/ | aafa- | agec | Adfa | g2 g>a | aafa- | agec | Ad "A"fa/g/ | f3 :|
|: e/f/ | g/f/e/d/ cg | a2 fd | d/e/f ^ge | aceg/a/ | b/a/g/f/ ea | g2 fa | bg- ga/g/ | f3 :|

**Comment by moinejf** [comment]
This problem should be fixed by the commit ef9a848.
Thanks.

**Comment by jnbearon** [comment]
Thankyou
Norman Bearon

------ Original Message ------
