### ISSUE TITLE
Missing diagrams when using %%chordnames

### ISSUE THREAD

**Issue by sonovice** [leesavide/abcm2ps#21]
When using `diagram` in conjunction with`chordnames`, diagrams for chords that no longer use common english notation are not shown.

```
X:1
%%chordnames C,D,E,F,G,A,H % German
%%diagram 1
K:C
V:1 treble
"C"C "D"D "E"E "F"F "G"G "A"A "B"B "C"c
```
![unbenannt](https://user-images.githubusercontent.com/8217108/38779828-1bdf2c30-40ce-11e8-8941-781ddee9c21a.PNG)

**Comment by moinejf** [comment]
There is no %%chordnames nor %%diagram in abcm2ps!

**Comment by sonovice** [comment]
Oh, I'm so sorry! I intended to post this issue to abc2svg.
