### ISSUE TITLE
bar-line thickness

### ISSUE THREAD

**Issue by nomanomanomanoma** [leesavide/abcm2ps#22]
It would be nice to be able to configure the width (thickness) of bar lines, so they look appropriate to more "substantial" fonts like Bravura.

**Comment by moinejf** [comment]
The thickness of the bar lines is defined by the PostScript function 'bar'.
You may redefine it by something like:
```%%beginps
/bar{M 1.5 SLW 0 exch RL stroke}!
%%endps
```
But this does not work with SVG output.

**Comment by nomanomanomanoma** [comment]
Very good, that will do!

**Comment by hkiel** [comment]
Is this documented somewhere (except in the source)?

**Comment by moinejf** [comment]
You can find some documentation on how to write PostScript code for abcm2ps in the sites of Guido Gonzato and Hudson Lacerda.
