### ISSUE TITLE
parse this abc to svg is width show error?  too small

### ISSUE THREAD

**Issue by match08** [leesavide/abcm2ps#49]
X:1
T:1.right hand
C:tom
%%scale 0.85
%%pagewidth 21.59cm
%%leftmargin 2.54cm
%%rightmargin 1.26cm
%%score { 1 | 2 }
L:1/4
Q:1/4=120
M:4/4
I:linebreak $
K:C
V:1 treble 
V:2 bass 
V:1
 !1!C4 | C4 | C4 | C4 |] %4
V:2
 z4 | z4 | z4 | z4 |] %4

**Comment by moinejf** [comment]
Sorry for I don't see/understand the problem.

**Comment by match08** [comment]
pagewidth 21.59cm , parse to svg is width look too small. all measure is at left, right a big space.
look this image:
![20181220101053](https://user-images.githubusercontent.com/616730/50260031-9aeb2d80-0441-11e9-926a-e2a3358af1ba.png)

**Comment by moinejf** [comment]
Use
%%stretchlast 1

**Comment by match08** [comment]
Thanks
