### ISSUE TITLE
subs.c:22:10: fatal error: 'pango/pangocairo.h' file not found

### ISSUE THREAD

**Issue by iooops** [leesavide/abcm2ps#5]
When I tried to install **abcm2ps-8.13.11** on my mac using the command
`make`

the following error occured:

> gcc -g -O2 -Wall -pipe -DHAVE_PANGO=1 -I. -I/usr/include/pango-1.0 -pthread -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/usr/include/pixman-1  -I/usr/include/libpng12 -I/usr/include/freetype2   -c -o subs.o subs.c
subs.c:22:10: fatal error: 'pango/pangocairo.h' file not found
#include <pango/pangocairo.h>
         ^
1 error generated.
make: *** [subs.o] Error 1

I have already installed pango on my mac(OS Sierra 10.12) and I am sure the folders are under the /usr/include directory.

Could anyone who has ever compiled the sources successfully give me a solution?

**Comment by iooops** [comment]
Ah.. Just use the command
`brew install abcm2ps`

And everything's all done.

**Comment by lewdlime** [comment]
I should note that if you do need pango support in abcm2ps on Mac, you should first run
```
brew install pango
```
then run `brew install abcm2ps`, as the `pango` Homebrew formula includes all the needed dependencies, and sets up the development files for other packages to use.
