### ISSUE TITLE
Segmentation fault when testing with `sample4.abc`

### ISSUE THREAD

**Issue by lewdlime** [leesavide/abcm2ps#6]
There seems to be a bug in running the test with `sample4.abc`, it consistently throws this error when running `make test`:

```bash
❯❯❯ ./abcm2ps -S -O sample4.ps sample4.abc
File sample4.abc
[1]    28843 segmentation fault (core dumped)  ./abcm2ps -S -O sample4.ps sample4.abc
```

For a full log, check here: <https://travis-ci.org/leesavide/abcm2ps/builds/253747134>

Any ideas what might be happening with this one?

**Comment by moinejf** [comment]
Fixed by commit 5adaa02f8bd8c7081ec52b200cc897af2dd9718d
