### ISSUE TITLE
Displays wrong rest value in score

### ISSUE THREAD

**Issue by timmbo9** [leesavide/abcm2ps#77]
After latest patch (re:issue #76) whole rest is displayed as quarter rest. Playback timing not affected.
[errabc.zip](https://github.com/leesavide/abcm2ps/files/5045194/errabc.zip)
[new.pdf](https://github.com/leesavide/abcm2ps/files/5045198/new.pdf)
[old.pdf](https://github.com/leesavide/abcm2ps/files/5045199/old.pdf)

**Comment by moinejf** [comment]
Should be fixed by commit 7e8986e.
Thanks.

**Comment by timmbo9** [comment]
Works for me. Thank you.
