### ISSUE TITLE
Missing coda

### ISSUE THREAD

**Issue by a773music** [leesavide/abcm2ps#8]
[missing_coda.txt](https://github.com/leesavide/abcm2ps/files/1351886/missing_coda.txt)

In the attached abc file the coda sign is not displayed with certain order of %%staves (see inside the abc). It seems to be due to the "@" guitar chord at the same place (in another voice)

**Comment by moinejf** [comment]
Hi Atte,
The bug should be fixed by the commit b62956076e3c828a99c6e18f24bcc163829c3e8f.
BTW, including ABC in the issue message is simpler than creating a separated file.

**Comment by a773music** [comment]
Thanks, it indeed seems fixed, thanks! Will include abc in the message in the future. Closing the issue!
