### ISSUE TITLE
Option parsing misses '-p'

### ISSUE THREAD

**Issue by sbeitzel** [leesavide/abcm2ps#9]
The command line argument processing doesn't detect the -p switch. For example:

```
[sbeitzel@PirateBook ~/src/github/abcm2ps]$ ./abcm2ps -p sample.abc
abcm2ps-8.13.16 (2017-10-24)
error: Unknown flag: -p ignored
File sample.abc
```

I'm attaching a patch which fixes this:
[pipeformat_patch.txt](https://github.com/leesavide/abcm2ps/files/1412834/pipeformat_patch.txt)

**Comment by moinejf** [comment]
Fixed. Thanks.

**Comment by sbeitzel** [comment]
Yep, that does the job.

Out of curiosity, why doesn't this application use getopt for parsing the options?

**Comment by moinejf** [comment]
This an old application, started almost 20 years ago, which was also working in M$-DOS.
Then, as the command line arguments may be complex (global parameters + files + possible parameters for each file), it is simpler to parse them manually.
